### ISSUE TITLE
different setups for each version?

### ISSUE THREAD

**Issue by BloodyRain2k** [pclewis/mcpatcher#35]
I was wondering if it would be possible to make MCPatcher assign the mod list to the version it was created with, major only of course so one for 1.8.1 - 1.8.2 - 1.8.3 etc.
That would make things way easier for people that still swap around a bit because not all mods are updated yet.

Maybe like mcpatcher_1_8.xml as settings file for 1.8 versions and select these upon changing (or creating) the original jar like minecraft-1.8.1.jar

**Comment by prupe** [comment]
I started on a feature like this a while back and ended up throwing the code out because it didn't work the way I wanted it.  A related feature that people have requested is the ability to create different mod profiles, even for the same version of Minecraft.  I decided to make another attempt that will address both needs.  Currently the feature is somewhat usable, and I'd like some feedback.  Would you mind being a beta tester once I get it working?

**Comment by BloodyRain2k** [comment]
I'd love to give it a try.

**Comment by prupe** [comment]
Done in version 2.1.2.
