### ISSUE TITLE
Bottom Of Water Not Colorized (Custom Colors)

### ISSUE THREAD

**Issue by MWisBest** [pclewis/mcpatcher#52]
The bottom of water is not colorized, as seen in Misa's texture pack. Place a bucket of water on a wall above you, and you'll see the bottom is gray. I noticed that MCPatcher might not be picking up on the colorizing of the bottom of water as the color is multiplied by 0.5F whereas the other ones multiply by 1.0F by default. If you are just finding the methods that multiply by 1.0F then you are missing the bottom colorizing. I'm not entirely certain as to how MCPatcher finds what to patch, so I can't really say for certain why it isn't picking up on it, but it isn't.

**Comment by prupe** [comment]
It's working for me (tested with Misa's on 1.2.5, 1.3.2, and 12w32a).  There's a patch specifically to deal with the bottom of water blocks because the vanilla code inexplicably doesn't use the color multiplier there.  Are you using other mods?  Is the line "[1] colorize bottom of water block" in your Patch Summary tab?

**Comment by MWisBest** [comment]
Yes I see that there, yet for some reason I don't see the bottom of water being colored. I tested with 1.3.1 and MCPatcher 2.4.1_02. And no, I'm not using any other mods. MCPatcher is all I used.

**Comment by MWisBest** [comment]
It's working fine now, so I'll close this.
