### ISSUE TITLE
MCPatcher Ignores the "mcpatcher-mods" Directory with Java 6

### ISSUE THREAD

**Issue by jetblackrx89** [pclewis/mcpatcher#66]
MCPatcher will fail to scan the "mcpatcher-mods" folder for mods if Java 6 is installed. Upgrading to Java 7 fixes the issue.

Tested using:
- Mac OS X 10.9.2
- mcpatcher-4.3.2_02
- MCDisableWheel-0.3 (search Google, top hit is a Github to this MCPatcher mod)

**Comment by prupe** [comment]
MCDisableWheel appears to have been compiled with Java 7, which is why it
can't be loaded in an earlier version:

javap -v mcdisablewheel.DisableMouseWheel
Classfile .../mcdisablewheel/DisableMouseWheel.class
  Last modified Feb 4, 2014; size 792 bytes
  MD5 checksum f54353aeb2b6940ae968cf38fa78ab67
  Compiled from "DisableMouseWheel.java"
public final class mcdisablewheel.DisableMouseWheel extends
com.prupe.mcpatcher.Mod
  SourceFile: "DisableMouseWheel.java"
-  minor version: 0  major version: 51\*  flags: ACC_PUBLIC, ACC_FINAL,
  ACC_SUPER

**Comment by jetblackrx89** [comment]
Sorry for this confusion. If it's a compilation issue with the mod, I will let the mod developer know on his github instead.
